// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip buttonSound;
		public AudioClip matchSound;
		public AudioClip completeSound;
		public AudioClip failSound;
		public AudioClip clickSound;
		public AudioClip clickBlockedSound;
	}
}